
name: 'Hugo Action for Asciidoc'

description: 'Action for build hugo while write in asciidoc.'

branding:
  icon: 'activity'
  color: 'orange'

inputs:
  source:
    description: 'hugo source repo.'
    required: true
  build:
    description: 'static file repo, such as github pages repo.'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.build }}
