
name: 'Hugo Action for Asciidoc'

description: 'Action for build hugo while write in asciidoc.'

branding:
  icon: 'activity'
  color: 'orange'

inputs:
  source-repo:
    description: 'hugo source repo.'
    required: true
  build-repo:
    description: 'static file repo, such as github pages repo.'
    required: true
  command:
    description: 'Exec command after build.'
    required: false
    default: ''

runs:
  using: 'docker'
  image: docker://c332030/hugo-asciidoctor
  args:
    - ${{ inputs.source-repo }}
    - ${{ inputs.build-repo }}
    - ${{ inputs.command }}
